#!/usr/bin/env python3
"""
Regenerates src/images/Logo120.h (the boot/sleep screen logo) from
assets/krosspop_logo.bmp. Run after editing the source image, then rebuild.

Packing: MSB-first, 1 bit/pixel, white=1/black=0, row-major top-down — matches
GfxRenderer::drawImage()'s expected layout, no rotation (unlike
scripts/convert_icon.py, which rotates for its own icon usage).
"""

import os

from PIL import Image

WIDTH, HEIGHT = 120, 120
THRESHOLD = 128
BYTES_PER_ROW = WIDTH // 8

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_PATH = os.path.join(PROJECT_ROOT, 'assets', 'krosspop_logo.bmp')
OUTPUT_PATH = os.path.join(PROJECT_ROOT, 'src', 'images', 'Logo120.h')


def pack_image(img):
    pixels = list(img.getdata())
    packed = []
    for y in range(HEIGHT):
        for x in range(0, WIDTH, 8):
            byte = 0
            for b in range(8):
                v = pixels[y * WIDTH + x + b]
                bit = 1 if v >= THRESHOLD else 0
                byte |= bit << (7 - b)
            packed.append(byte)
    return packed


def format_header(packed):
    lines = [
        '#pragma once',
        '#include <cstdint>',
        '',
        "// 'krosspop', 120x120px — generated by scripts/gen_boot_logo.py from assets/krosspop_logo.bmp",
        'static const uint8_t Logo120[] = {',
    ]
    for i in range(0, len(packed), 16):
        row = ', '.join(f'0x{v:02x}' for v in packed[i:i + 16])
        lines.append(f'    {row},')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};')
    lines.append(f'static_assert(sizeof(Logo120) == {WIDTH * HEIGHT // 8}, "Logo120 must be exactly {WIDTH}x{HEIGHT} / 8 bytes");')
    return '\n'.join(lines) + '\n'


def main():
    img = Image.open(SOURCE_PATH).convert('L')
    if img.size != (WIDTH, HEIGHT):
        raise SystemExit(f'{SOURCE_PATH} is {img.size}, expected {WIDTH}x{HEIGHT}')
    img = img.rotate(90, expand=True)  # 90 degrees counterclockwise

    packed = pack_image(img)
    header = format_header(packed)

    with open(OUTPUT_PATH, 'w') as f:
        f.write(header)
    print(f'Wrote {OUTPUT_PATH} ({len(packed)} bytes packed)')


if __name__ == '__main__':
    main()
